Html
theodoku/Hello_Microverse pull request #1
Opened 2022-10-26 10:25 UTC by theodoku

2022-10-26 10:51 UTC, Alfredbis29 requested changes
Hi @theodoku ,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] Good commit messages :heavy_check_mark: 
- [ ] Correct Github FLow :heavy_check_mark: 

## Required Changes :recycle:

- [ ] I noticed that your Pull Request is not descriptive , please kindly make sure your PR has description :upside_down_face: :wink:

- [ ] I can't see your `README`file as well , follow this [Readme Template](https://github.com/microverseinc/readme-template/blob/master/README.md) to make a professional Readme  

- [ ] Please kindly check the comments under the review for more details :point_down: :point_down: 

**Cheers and Happy coding! :clap::clap::clap:**

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-26 10:51 UTC, Alfredbis29 commented on A. html
> +</body>
- [ ] Great job so far , but there is something you still need to work on , we can see your `Hello MIcroverse` in your body , please fix this so that your project will get approval :wink:

2022-10-26 10:51 UTC, Alfredbis29 commented on A test.md
> +This file should be ignored by git
- [ ] As required to this project your `test.md`file should be ignore in the `gitignore`file please fix this :wink:

2022-10-26 14:49 UTC, theodoku commented
Hello Alfred,
Please I have worked on the changes. How can I submit?
Thanks


On Wed, Oct 26, 2022 at 10:51 AM Alfred Bisimwa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @theodoku <https://github.com/theodoku> ,
>
> Good job so far!
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif>
> Highlights
>
>    - Good commit messages ✔️
>    - Correct Github FLow ✔️
>
> Required Changes ♻️
>
>    -
>
>    I noticed that your Pull Request is not descriptive , please kindly
>    make sure your PR has description 🙃 😉
>    -
>
>    I can't see your READMEfile as well , follow this Readme Template
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    to make a professional Readme
>    -
>
>    Please kindly check the comments under the review for more details 👇
>    👇
>
> *Cheers and Happy coding! 👏👏👏*
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In A. html
> <https://github.com/theodoku/Hello_Microverse/pull/1#discussion_r1005515973>
> :
>
> > +<body>
>
> +
>
> +</body>
>
>
>
>    - Great job so far , but there is something you still need to work on
>    , we can see your Hello MIcroverse in your body , please fix this so
>    that your project will get approval 😉
>
> ------------------------------
>
> In A test.md
> <https://github.com/theodoku/Hello_Microverse/pull/1#discussion_r1005517823>
> :
>
> > @@ -0,0 +1 @@
>
> +This file should be ignored by git
>
>
>
>    - As required to this project your test.mdfile should be ignore in the
>    gitignorefile please fix this 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/theodoku/Hello_Microverse/pull/1#pullrequestreview-1156272772>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2G55DMNFN4FKH7T7B2CZDDWFEEL3ANCNFSM6AAAAAARO24ZEQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-27 12:36 UTC, theodoku commented on A. html
> +</body>
It has been fixed

2022-10-27 12:37 UTC, theodoku commented on A test.md
> +This file should be ignored by git
It has been fixed

2022-10-27 13:06 UTC, franclobo requested changes
Hi @theodoku, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good README file ✔️ 
- Correct Github flow ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Please pay attention to the requirements from the last code reviewer:

- [ ] I noticed that your Pull Request is not descriptive, please kindly make sure your PR has description 🙃 😉

![image](https://user-images.githubusercontent.com/58642949/198291000-d0fda7e0-6a07-4463-8677-0baf2f6d23ed.png)

## Optional suggestions

- [ ] **[OPTIONAL]** There should be one folder inside the `.github` folder, it is `workflows/linters.yml`, please 🙏🏽 delete the rest.

![image](https://user-images.githubusercontent.com/58642949/198292404-4f6b4d47-6c0b-41cd-90b4-d5b73ab04ea0.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 13:06 UTC, franclobo commented on README.md
>  👤 **Author1**
- [ ] **[OPTIONAL]** Please replase **`Author1`** with your name.

2022-10-28 13:25 UTC, theodoku commented on README.md
>  👤 **Author1**
Author1 changed to Theo

2022-10-28 14:21 UTC, theodoku commented
Author1 name changed to theo

2022-10-28 15:00 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 
Hi @theodoku , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![bunnys](https://user-images.githubusercontent.com/99246359/198664049-311595ae-29bb-4153-b9c9-0ab60bf5f60a.gif)

## Highlights 💯 
- Github flow used ✔️
- Professional Readme ✔️
- node_modules and test.md file ignored ✔️

## Optional suggestions

How are you @theodoku? Thank you for implementing the required changes by the previous code reviewers. 

- I would like to kindly suggest that for subsequent projects, always ensure to install all run linters files. You can only request for review when your linters have passed (with green tick) ✔️ 

- Kindly Ensure that your feature branch is named after the current feature you are working on (e.g "create_navbar", "hello_microverse", "portfolio-setup" e.t.c) ✔️

- Kindly make sure that your commit messages are descriptive. By this, I mean it should be about an update you just implemented in your project (e.g "add project toolbar", "update readme file", "add works container content" e.t.c) ✔️

- Kindly ensure to have a descriptive pull request that summarizes all the tasks you have just done.✔️

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 07:43 UTC, merged